"""add species regulation fields

Revision ID: 1132a12a0455
Revises: 18144e3767ba
Create Date: 2026-06-30 19:10:19.223145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1132a12a0455'
down_revision: Union[str, None] = '18144e3767ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('species', sa.Column('min_size', sa.String(length=50), nullable=True))
    op.add_column('species', sa.Column('bag_limit', sa.String(length=50), nullable=True))
    op.add_column('species', sa.Column('regulation_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('species', 'regulation_notes')
    op.drop_column('species', 'bag_limit')
    op.drop_column('species', 'min_size')
    # ### end Alembic commands ###
