"""add species classifier_description

Revision ID: 2db968b571e0
Revises: 567678d1ef14
Create Date: 2026-06-30 15:15:23.085160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db968b571e0'
down_revision: Union[str, None] = '567678d1ef14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('species', sa.Column('classifier_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('species', 'classifier_description')
    # ### end Alembic commands ###
