"""add hashed_password to users

Revision ID: 567678d1ef14
Revises: 5a7c6a52320d
Create Date: 2026-06-30 13:23:11.971287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '567678d1ef14'
down_revision: Union[str, None] = '5a7c6a52320d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.String(length=255), nullable=False, server_default=''))
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('hashed_password', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('hashed_password')
    # ### end Alembic commands ###
