"""init schema

Revision ID: 5a7c6a52320d
Revises: 
Create Date: 2026-06-30 13:03:38.069410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a7c6a52320d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(length=100), nullable=False),
    sa.Column('scientific_name', sa.String(length=150), nullable=True),
    sa.Column('habitat_description', sa.Text(), nullable=True),
    sa.Column('typical_size_range', sa.String(length=100), nullable=True),
    sa.Column('season_notes', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('silhouette_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_species_common_name'), 'species', ['common_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_display_name'), 'users', ['display_name'], unique=True)
    op.create_table('catches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('caught_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catches_caught_at'), 'catches', ['caught_at'], unique=False)
    op.create_index(op.f('ix_catches_length'), 'catches', ['length'], unique=False)
    op.create_index(op.f('ix_catches_species_id'), 'catches', ['species_id'], unique=False)
    op.create_index(op.f('ix_catches_user_id'), 'catches', ['user_id'], unique=False)
    op.create_index(op.f('ix_catches_weight'), 'catches', ['weight'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catches_weight'), table_name='catches')
    op.drop_index(op.f('ix_catches_user_id'), table_name='catches')
    op.drop_index(op.f('ix_catches_species_id'), table_name='catches')
    op.drop_index(op.f('ix_catches_length'), table_name='catches')
    op.drop_index(op.f('ix_catches_caught_at'), table_name='catches')
    op.drop_table('catches')
    op.drop_index(op.f('ix_users_display_name'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_species_common_name'), table_name='species')
    op.drop_table('species')
    # ### end Alembic commands ###
